### ISSUE TITLE
Default user setup überarbeiten

### ISSUE THREAD

**Issue by rhenck** [iqb-berlin/testcenter-setup#18]
Für eine auslieferbare Produktivinstallation sollten wir überlegen welche superuser, testlogins und workspaces vorhanden sein sollen. Und diese ggf. in der Installationsroutine abfragen.

**Comment by paflov** [comment]
Das init-script erstellt einen super-user und einen workspace mit allen beispieldateien, wenn nicht vorhanden. Damit sind auch alle möglichen Test-Logins beispielhaft vorhanden. Reicht das nicht?

**Comment by rhenck** [comment]
Im Gegenteil, die Frage ist braucht man das? Für DEV ist das gut so, aber in der Produktivumgebung vllt nicht so sehr. Zumal nicht so gut ist, dass Logins erstellt werden, die jedermann in der Readme nachlesen kann. Deswegen der Ansatz, dass man beim Installieren abfragt, ob user angelegt werden sollen und wie diese heissen und deren PW ist etc.

**Comment by paflov** [comment]
Ja. Man kann dem init-script ja auch andere Daten übergeben oder sagen, dass es gar nichts anlegen soll. Eine Installation ohne einen einzigen (superadmin-)user ist allerdings nicht benutzbar.

**Comment by paflov** [comment]
Auf den initialen Superuser kann man also nicht verzichten. Der Rest - also ich persönlich finde es eigentlich auch fürs Produktiv-Setup ganz nett, wenn Beispieldaten da sind und man direkt sich einloggen kann und gucken kann ob alles funktioniert usw.

Aber wenn du es unbedingt loswerden willst, wäre es einfach: 
Ich könnte in das Initscript einen Paramater einfügen der sagt, ob er Testdaten anlegen soll. Dann könnte beim Prod-Setup den Beispielcontent überspringen. 
Kann sogar sein, müsste ich aber prüfen, dass, wenn man keinen Workspace-Namen angibt auch keiner angelegt wird, dann müsste von backend-seite her gar nichts umgebaut werden.
