### ISSUE TITLE
Überarbeitung der CSV Reports

### ISSUE THREAD

**Issue by svwolter** [iqb-berlin/testcenter-setup#24]

**Comment by paflov** [comment]
Ich versteh eigentlich nicht, warum das ein Setup-Ticket ist.

**Comment by svwolter** [comment]
Kein Setup Thema im eigentlichen Sinne, da aber Frontend- und Backend betroffen sind, dachte ich es wäre besser. auch ein Setup-Ticket als übergeordnete Ebene anzulegen, sodass Front- und Backend im Setup-Projekt nicht auseinander laufen können.
